### ISSUE TITLE
ModuleNotFoundError: No module named 'imghdr'

### ISSUE THREAD

**Issue by hustcer** [dfface/xml2epub#40]
```python
import xml2epub

## create an empty eBook
book = xml2epub.Epub("My New E-book Name")
## create chapters by url
#### custom your own cover image
chapter0 = xml2epub.create_chapter_from_string("https://cdn.jsdelivr.net/gh/dfface/img0@master/2022/02-10-0R7kll.png", title='cover', strict=False)
#### create chapter objects
chapter1 = xml2epub.create_chapter_from_url("https://dev.to/devteam/top-7-featured-dev-posts-from-the-past-week-h6h")
chapter2 = xml2epub.create_chapter_from_url("https://dev.to/ks1912/getting-started-with-docker-34g6")
## add chapters to your eBook
book.add_chapter(chapter0)
book.add_chapter(chapter1)
book.add_chapter(chapter2)
## generate epub file
book.create_epub("/tmp/")
```

Run the above code will got the following error:
```console
Traceback (most recent call last):
  File "~/run/moonbit.py", line 1, in <module>
    import xml2epub
  File "~/.venv/lib/python3.13/site-packages/xml2epub/__init__.py", line 1, in <module>
    from .chapter import create_chapter_from_string
  File "~/.venv/lib/python3.13/site-packages/xml2epub/chapter.py", line 7, in <module>
    import imghdr
ModuleNotFoundError: No module named 'imghdr'
```

**Comment by igorlima** [comment]
This issue points to some changes in the Python standard library that have impacted the `xml2epub` package.

The [PEP 594](https://peps.python.org/pep-0594/#imghdr) has removed several outdated modules, including the [`imghdr` module](https://peps.python.org/pep-0594/#imghdr).

For a similar discussion and solution, you can check out this StackOverflow thread:
- https://stackoverflow.com/questions/79144437/how-to-resolve-no-module-named-imghdr-error-in-python-3-13-with-tweepy

If you'd like to try out this fix, you can install it directly from the Git branch:
```sh
# Install directly from the Git branch
pip3 install -I git+https://github.com/igorlima/xml2epub.git@address-issue-40
```

Additionally, there is an open pull request addressing this issue:
- https://github.com/dfface/xml2epub/pull/41

Once you've tested it, please leave a supportive comment. Your feedback and thumbs-up can help encourage the maintainer to approve it.

👍

**Comment by Mirochill** [comment]
This looks fixed in the current source and published package metadata now.

PR #41 was merged, and `main` now declares `standard-imghdr` in both `requirements.txt` and `setup.py`. The current PyPI release metadata for `xml2epub==2.6.11` also lists `standard-imghdr`, so the remaining `import imghdr` in `xml2epub/chapter.py` should be supplied by that backport on Python 3.13.

If this is still reproducible with a fresh install of `xml2epub==2.6.11`, an updated install log would help narrow down whether the environment is missing the declared dependency. Otherwise this issue may be ready to close.
